# Generated by Django 4.2.4 on 2023-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
