# Generated by Django 4.2.4 on 2023-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NEWS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
