# Generated by Django 4.2.4 on 2023-11-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0004_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
